from django.db import models
from django.contrib.auth.models import AbstractUser,UserManager
from django.db.models.signals import post_save
from multiselectfield import MultiSelectField
from django.core.validators import RegexValidator
# from django.contrib.auth.models import PermissionsMixin
import uuid
from django.utils import timezone

phone_validator = RegexValidator(r"^(\+?\d{0,4})?\s?-?\s?(\(?\d{3}\)?)\s?-?\s?(\(?\d{3}\)?)\s?-?\s?(\(?\d{4}\)?)?$", "The phone number provided is invalid")



class User(AbstractUser):
    is_client = models.BooleanField(default=False)
    is_freelancer = models.BooleanField(default=False)
    is_student = models.BooleanField(default=False)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_verified = models.BooleanField(default=False)
    has_paid = models.BooleanField(default=False)
    last_login = models.DateTimeField(default=timezone.now)

def __str__(self):
    return self.first_name


Lang_choice = (
    ('English', 'English'),
    ('Yoruba', 'Yoruba'),
    ('Igbo', 'Igbo'),
    ('Hausa', 'Hausa')
)

BANK_CHOICES = (
('Access Bank Plc','Access Bank Plc'),
('Fidelity Bank Plc','Fidelity Bank Plc'),
('First City Monument Bank Limited','First City Monument Bank Limited'),
('First Bank of Nigeria Limited','First Bank of Nigeria Limited'),
('Guaranty Trust Holding Company Plc','Guaranty Trust Holding Company Plc'),
('Union Bank of Nigeria Plc','Union Bank of Nigeria Plc'),
('United Bank for Africa Plc','United Bank for Africa Plc'),
('Zenith Bank Plc','Zenith Bank Plc'),
('Citibank Nigeria Limited','Citibank Nigeria Limited'),
('Ecobank Nigeria','Ecobank Nigeria'),
('Heritage Bank Plc','Heritage Bank Plc'),
('Keystone Bank Limited','Keystone Bank Limited'),
('Polaris Bank','Polaris Bank'),
('Stanbic IBTC Bank Plc','Stanbic IBTC Bank Plc'),
('Standard Chartered','Standard Chartered'),
('Sterling Bank Plc','Sterling Bank Plc'),
('Titan Trust Bank Limited','Titan Trust Bank Limited'),
('Unity Bank Plc','Unity Bank Plc'),
('Wema Bank Plc','Wema Bank Plc'),
('Globus Bank Limited','Globus Bank Limited'),
('Parallex Bank Limited','Parallex Bank Limited'),
('PremiumTrust Bank Limited','PremiumTrust Bank Limited'),
('Providus Bank Limited','Providus Bank Limited'),
('SunTrust Bank Nigeria Limited','SunTrust Bank Nigeria Limited'),
('Jaiz Bank Plc','Jaiz Bank Plc'),
('LOTUS BANK','LOTUS BANK'),
('TAJBank Limited','TAJBank Limited'),
('Mutual Trust Microfinance Bank','Mutual Trust Microfinance Bank'),
('Rephidim Microfinance Bank','Rephidim Microfinance Bank'),
('Shepherd Trust Microfinance Bank','Shepherd Trust Microfinance Bank'),
('Empire Trust Microfinance Bank','Empire Trust Microfinance Bank'),
('Finca Microfinance Bank Limited','Finca Microfinance Bank Limited'),
('Fina Trust Microfinance Bank','Fina Trust Microfinance Bank'),
('Accion Microfinance Bank','Accion Microfinance Bank'),
('Peace Microfinance Bank','Peace Microfinance Bank'),
('Infinity Microfinance Bank','Infinity Microfinance Bank'),
('Pearl Microfinance Bank Limited','Pearl Microfinance Bank Limited'),
('Covenant Microfinance Bank Ltd','Covenant Microfinance Bank Ltd'),
('Advans La Fayette Microfinance Bank','Advans La Fayette Microfinance Bank'),
('Sparkle Bank','Sparkle Bank'),
('Kuda Bank','Kuda Bank'),
('Opay','Opay'),
('Palmpay','Palmpay'),
('Rubies Bank','Rubies Bank'),
('VFD Microfinance Bank','VFD Microfinance Bank'),
('Mint Finex MFB','Mint Finex MFB'),
('Mkobo MFB','Mkobo MFB'),
('Coronation Merchant Bank','Coronation Merchant Bank'),
('FBNQuest Merchant Bank','FBNQuest Merchant Bank'),
('FSDH Merchant Bank','FSDH Merchant Bank'),
('Rand Merchant Bank','Rand Merchant Bank'),
('Nova Merchant Bank','Nova Merchant Bank')
)

STATE_CHOICES = (
('  Abia ' , '  Abia '),   
(' Adamawa',' Adamawa	'),
 (' Akwa Ibom', ' Akwa Ibom'),	
 (' Anambra', ' Anambra'),
 (' Bauchi	', ' Bauchi	'),
 (' Bayelsa	', ' Bayelsa	'),
 (' Benue	', ' Benue	'),
 (' Borno	', ' Borno	'),
 (' Cross River', ' Cross River'),
 (' Delta	', ' Delta	'),
 (' Ebonyi' ,' Ebonyi'),
 (' Edo	',' Edo	'),
 (' Ekiti	' ,' Ekiti	'),
 (' Enugu	', ' Enugu	' ),
 (' Gombe' ,' Gombe'),	
 (' Imo', ' Imo' ),
 (' Jigawa',' Jigawa'),
 (' Kaduna',' Kaduna'),	
 (' Kano',' Kano'),
 (' Katsina	', ' Katsina'),
 (' Kebbi	',' Kebbi	'),
 (' Kogi	',' Kogi	'),
 (' Kwara	', 'Kwara'),
 (' Lagos	',' Lagos	'),
 (' Nasarawa' ,' Nasarawa' ),
 (' Niger	' , ' Niger	'),
 (' Ogun	',' Ogun	'),
 (' Ondo	',' Ondo	'),
 (' Osun	', ' Osun	'),
 (' Oyo	', ' Oyo	'),
 (' Plateau', ' Plateau'),
 (' Rivers', ' Rivers'),
 (' Sokoto	', ' Sokoto	'),
 (' Taraba	', ' Taraba	'),
 (' Yobe	',' Yobe	'),
 (' Zamfara	', ' Zamfara '),
 (' Abuja', ' Abuja'),
    )

LGA_CHOICES = ( 
('Aba North','Aba North'),
('Aba South','Aba South'),
('Abadam','Abadam'),
('Abaji','Abaji'),
('Abak','Abak'),
('Abakaliki','Abakaliki'),
('Abeokuta North','Abeokuta North'),
('Abeokuta South','Abeokuta South'),
('Abi','Abi'),
('Aboh Mbaise','Aboh Mbaise'),
('Abua/Odual','Abua/Odual'),
('Abuja Municipal Area Council','Abuja Municipal Area Council'),
('Adavi','Adavi'),
('Ado','Ado'),
('Ado Ekiti','Ado Ekiti'),
('Ado-Odo/Ota','Ado-Odo/Ota'),
('Afijio','Afijio'),
('Afikpo North','Afikpo North'),
('Afikpo South (Edda)','Afikpo South (Edda)'),
('Agaie','Agaie'),
('Agatu','Agatu'),
('Agege','Agege'),
('Aguata','Aguata'),
('Agwara','Agwara'),
('Ahiazu Mbaise','Ahiazu Mbaise'),
('Ahoada East','Ahoada East'),
('Ahoada West','Ahoada West'),
('Aiyedaade','Aiyedaade'),
('Aiyedire','Aiyedire'),
('Ajaokuta','Ajaokuta'),
('Ajeromi-Ifelodun','Ajeromi-Ifelodun'),
('Ajingi','Ajingi'),
('Akamkpa','Akamkpa'),
('Akinyele','Akinyele'),
('Akko','Akko'),
('Akoko North-East','Akoko North-East'),
('Akoko North-West','Akoko North-West'),
('Akoko South-East','Akoko South-East'),
('Akoko South-West','Akoko South-West'),
('Akoko-Edo','Akoko-Edo'),
('Akpabuyo','Akpabuyo'),
('Akuku-Toru','Akuku-Toru'),
('Akure North','Akure North'),
('Akure South','Akure South'),
('Akwanga','Akwanga'),
('Albasu','Albasu'),
('Aleiro','Aleiro'),
('Alimosho','Alimosho'),
('Alkaleri','Alkaleri'),
('Amuwo-Odofin','Amuwo-Odofin'),
('Anambra East','Anambra East'),
('Anambra West','Anambra West'),
('Anaocha','Anaocha'),
('Andoni','Andoni'),
('Aninri','Aninri'),
('Aniocha North','Aniocha North'),
('Aniocha South','Aniocha South'),
('Anka','Anka'),
('Ankpa','Ankpa'),
('Apa','Apa'),
('Apapa','Apapa'),
('Ardo Kola','Ardo Kola'),
('Arewa','Arewa'),
('Argungu','Argungu'),
('Arochukwu','Arochukwu'),
('Asa','Asa'),
('Asari-Toru','Asari-Toru'),
('Askira/Uba','Askira/Uba'),
('Atakunmosa East','Atakunmosa East'),
('Atakunmosa West','Atakunmosa West'),
('Atiba','Atiba'),
('Atisbo','Atisbo'),
('Augie','Augie'),
('Auyo','Auyo'),
('Awe','Awe'),
('Awgu','Awgu'),
('Awka North','Awka North'),
('Awka South','Awka South'),
('Ayamelum','Ayamelum'),
('Babura','Babura'),
('Badagry','Badagry'),
('Bade','Bade'),
('Bagudo','Bagudo'),
('Bagwai','Bagwai'),
('Bakassi','Bakassi'),
('Bakori','Bakori'),
('Bakura','Bakura'),
('Balanga','Balanga'),
('Bali','Bali'),
('Bama','Bama'),
('Barkin Ladi','Barkin Ladi'),
('Baruten','Baruten'),
('Bassa','Bassa'),
('Bassa','Bassa'),
('Batagarawa','Batagarawa'),
('Batsari','Batsari'),
('Bauchi','Bauchi'),
('Baure','Baure'),
('Bayo','Bayo'),
('Bebeji','Bebeji'),
('Bekwarra','Bekwarra'),
('Bende','Bende'),
('Biase','Biase'),
('Bichi','Bichi'),
('Bida','Bida'),
('Billiri','Billiri'),
('Bindawa','Bindawa'),
('Binji','Binji'),
('Biriniwa','Biriniwa'),
('Birnin Gwari','Birnin Gwari'),
('Birnin Kebbi','Birnin Kebbi'),
('Birnin Kudu','Birnin Kudu'),
('Birnin Magaji/Kiyaw','Birnin Magaji/Kiyaw'),
('Biu','Biu'),
('Bodinga','Bodinga'),
('Bogoro','Bogoro'),
('Boki','Boki'),
('Bokkos','Bokkos'),
('Boluwaduro','Boluwaduro'),
('Bomadi','Bomadi'),
('Bonny','Bonny'),
('Borgu','Borgu'),
('Boripe','Boripe'),
('Bosso','Bosso'),
('Brass','Brass'),
('Buji','Buji'),
('Bukkuyum','Bukkuyum'),
('Bungudu','Bungudu'),
('Bunkure','Bunkure'),
('Bunza','Bunza'),
('Bursari','Bursari'),
('Buruku','Buruku'),
('Burutu','Burutu'),
('Bwari','Bwari'),
('Calabar Municipal','Calabar Municipal'),
('Calabar South','Calabar South'),
('Chafe','Chafe'),
('Chanchaga','Chanchaga'),
('Charanchi','Charanchi'),
('Chibok','Chibok'),
('Chikun','Chikun'),
('Dala','Dala'),
('Damaturu','Damaturu'),
('Damban','Damban'),
('Dambatta','Dambatta'),
('Damboa','Damboa'),
('Dan Musa','Dan Musa'),
('Dandi','Dandi'),
('Dandume','Dandume'),
('Dange Shuni','Dange Shuni'),
('Danja','Danja'),
('Danko-Wasagu','Danko-Wasagu'),
('Darazo','Darazo'),
('Dass','Dass'),
('Daura','Daura'),
('Dawakin Kudu','Dawakin Kudu'),
('Dawakin Tofa','Dawakin Tofa'),
('Degema','Degema'),
('Dekina','Dekina'),
('Demsa','Demsa'),
('Dikwa','Dikwa'),
('Doguwa','Doguwa'),
('Doma','Doma'),
('Donga','Donga'),
('Dukku','Dukku'),
('Dunukofia','Dunukofia'),
('Dutse','Dutse'),
('Dutsi','Dutsi'),
('Dutsin Ma','Dutsin Ma'),
('Eastern Obolo','Eastern Obolo'),
('Ebonyi','Ebonyi'),
('Edati','Edati'),
('Ede North','Ede North'),
('Ede South','Ede South'),
('Edu','Edu'),
('Efon','Efon'),
('Egbeda','Egbeda'),
('Egbedore','Egbedore'),
('Egor','Egor'),
('Ehime Mbano','Ehime Mbano'),
('Ejigbo','Ejigbo'),
('Ekeremor','Ekeremor'),
('Eket','Eket'),
('Ekiti','Ekiti'),
('Ekiti East','Ekiti East'),
('Ekiti South-West','Ekiti South-West'),
('Ekiti West','Ekiti West'),
('Ekwusigo','Ekwusigo'),
('Eleme','Eleme'),
('Emuoha','Emuoha'),
('Emure','Emure'),
('Enugu East','Enugu East'),
('Enugu North','Enugu North'),
('Enugu South','Enugu South'),
('Epe','Epe'),
('Esan Central','Esan Central'),
('Esan North-East','Esan North-East'),
('Esan South-East','Esan South-East'),
('Esan West','Esan West'),
('Ese Odo','Ese Odo'),
('Esit Eket','Esit Eket'),
('Essien Udim','Essien Udim'),
('Etche','Etche'),
('Ethiope East','Ethiope East'),
('Ethiope West','Ethiope West'),
('Eti Osa','Eti Osa'),
('Etim Ekpo','Etim Ekpo'),
('Etinan','Etinan'),
('Etsako Central','Etsako Central'),
('Etsako East','Etsako East'),
('Etsako West','Etsako West'),
('Etung','Etung'),
('Ewekoro','Ewekoro'),
('Ezeagu','Ezeagu'),
('Ezinihitte','Ezinihitte'),
('Ezza North','Ezza North'),
('Ezza South','Ezza South'),
('Fagge','Fagge'),
('Fakai','Fakai'),
('Faskari','Faskari'),
('Federal Capital Territory','Federal Capital Territory'),
('Fika','Fika'),
('Fufure','Fufure'),
('Funakaye','Funakaye'),
('Fune','Fune'),
('Funtua','Funtua'),
('Gabasawa','Gabasawa'),
('Gada','Gada'),
('Gagarawa','Gagarawa'),
('Gamawa','Gamawa'),
('Ganjuwa','Ganjuwa'),
('Ganye','Ganye'),
('Garki','Garki'),
('Garko','Garko'),
('Garun Mallam','Garun Mallam'),
('Gashaka','Gashaka'),
('Gassol','Gassol'),
('Gaya','Gaya'),
('Gayuk','Gayuk'),
('Gbako','Gbako'),
('Gboko','Gboko'),
('Gbonyin','Gbonyin'),
('Geidam','Geidam'),
('Gezawa','Gezawa'),
('Giade','Giade'),
('Girei','Girei'),
('Giwa','Giwa'),
('Gokana','Gokana'),
('Gombe','Gombe'),
('Gombi','Gombi'),
('Goronyo','Goronyo'),
('Gubio','Gubio'),
('Gudu','Gudu'),
('Gujba','Gujba'),
('Gulani','Gulani'),
('Guma','Guma'),
('Gumel','Gumel'),
('Gummi','Gummi'),
('Gurara','Gurara'),
('Guri','Guri'),
('Gusau','Gusau'),
('Guzamala','Guzamala'),
('Gwadabawa','Gwadabawa'),
('Gwagwalada','Gwagwalada'),
('Gwale','Gwale'),
('Gwandu','Gwandu'),
('Gwaram','Gwaram'),
('Gwarzo','Gwarzo'),
('Gwer East','Gwer East'),
('Gwer West','Gwer West'),
('Gwiwa','Gwiwa'),
('Gwoza','Gwoza'),
('Hadejia','Hadejia'),
('Hawul','Hawul'),
('Hong','Hong'),
('Ibadan North','Ibadan North'),
('Ibadan North-East','Ibadan North-East'),
('Ibadan North-West','Ibadan North-West'),
('Ibadan South-East','Ibadan South-East'),
('Ibadan South-West','Ibadan South-West'),
('Ibaji','Ibaji'),
('Ibarapa Central','Ibarapa Central'),
('Ibarapa East','Ibarapa East'),
('Ibarapa North','Ibarapa North'),
('Ibeju-Lekki','Ibeju-Lekki'),
('Ibeno','Ibeno'),
('Ibesikpo Asutan','Ibesikpo Asutan'),
('Ibi','Ibi'),
('Ibiono-Ibom','Ibiono-Ibom'),
('Idah','Idah'),
('Idanre','Idanre'),
('Ideato North','Ideato North'),
('Ideato South','Ideato South'),
('Idemili North','Idemili North'),
('Idemili South','Idemili South'),
('Ido','Ido'),
('Ido Osi','Ido Osi'),
('Ifako-Ijaiye','Ifako-Ijaiye'),
('Ife Central','Ife Central'),
('Ife East','Ife East'),
('Ife North','Ife North'),
('Ife South','Ife South'),
('Ifedayo','Ifedayo'),
('Ifedore','Ifedore'),
('Ifelodun','Ifelodun'),
('Ifelodun','Ifelodun'),
('Ifo','Ifo'),
('Igabi','Igabi'),
('Igalamela Odolu','Igalamela Odolu'),
('Igbo Etiti','Igbo Etiti'),
('Igbo Eze North','Igbo Eze North'),
('Igbo Eze South','Igbo Eze South'),
('Igueben','Igueben'),
('Ihiala','Ihiala'),
('Ihitte/Uboma','Ihitte/Uboma'),
('Ijebu East','Ijebu East'),
('Ijebu North','Ijebu North'),
('Ijebu North East','Ijebu North East'),
('Ijebu Ode','Ijebu Ode'),
('Ijero','Ijero'),
('Ijumu','Ijumu'),
('Ika','Ika'),
('Ika North East','Ika North East'),
('Ika South','Ika South'),
('Ikara','Ikara'),
('Ikeduru','Ikeduru'),
('Ikeja','Ikeja'),
('Ikenne','Ikenne'),
('Ikere','Ikere'),
('Ikole','Ikole'),
('Ikom','Ikom'),
('Ikono','Ikono'),
('Ikorodu','Ikorodu'),
('Ikot Abasi','Ikot Abasi'),
('Ikot Ekpene','Ikot Ekpene'),
('Ikpoba Okha','Ikpoba Okha'),
('Ikwerre','Ikwerre'),
('Ikwo','Ikwo'),
('Ikwuano','Ikwuano'),
('Ila','Ila'),
('Ilaje','Ilaje'),
('Ile Oluji/Okeigbo','Ile Oluji/Okeigbo'),
('Ilejemeje','Ilejemeje'),
('Ilesa East','Ilesa East'),
('Ilesa West','Ilesa West'),
('Illela','Illela'),
('Ilorin East','Ilorin East'),
('Ilorin South','Ilorin South'),
('Ilorin West','Ilorin West'),
('Imeko Afon','Imeko Afon'),
('Ingawa','Ingawa'),
('Ini','Ini'),
('Ipokia','Ipokia'),
('Irele','Irele'),
('Irepo','Irepo'),
('Irepodun','Irepodun'),
('Irepodun','Irepodun'),
('Irepodun/Ifelodun','Irepodun/Ifelodun'),
('Irewole','Irewole'),
('Isa','Isa'),
('Ise/Orun','Ise/Orun'),
('Iseyin','Iseyin'),
('Ishielu','Ishielu'),
('Isi Uzo','Isi Uzo'),
('Isiala Mbano','Isiala Mbano'),
('Isiala Ngwa North','Isiala Ngwa North'),
('Isiala Ngwa South','Isiala Ngwa South'),
('Isin','Isin'),
('Isokan','Isokan'),
('Isoko North','Isoko North'),
('Isoko South','Isoko South'),
('Isu','Isu'),
('Isuikwuato','Isuikwuato'),
('Itas/Gadau','Itas/Gadau'),
('Itesiwaju','Itesiwaju'),
('Itu','Itu'),
('Ivo','Ivo'),
('Iwajowa','Iwajowa'),
('Iwo','Iwo'),
('Izzi','Izzi'),
('Jaba','Jaba'),
('Jada','Jada'),
('Jahun','Jahun'),
('Jakusko','Jakusko'),
('Jalingo','Jalingo'),
('Jama"are','Jama"are'),
('Jega','Jega'),
('Jema"a','Jema"a'),
('Jere','Jere'),
('Jibia','Jibia'),
('Jos East','Jos East'),
('Jos North','Jos North'),
('Jos South','Jos South'),
('Kabba/Bunu','Kabba/Bunu'),
('Kabo','Kabo'),
('Kachia','Kachia'),
('Kaduna North','Kaduna North'),
('Kaduna South','Kaduna South'),
('Kafin Hausa','Kafin Hausa'),
('Kafur','Kafur'),
('Kaga','Kaga'),
('Kagarko','Kagarko'),
('Kaiama','Kaiama'),
('Kaita','Kaita'),
('Kajola','Kajola'),
('Kajuru','Kajuru'),
('Kala/Balge','Kala/Balge'),
('Kalgo','Kalgo'),
('Kaltungo','Kaltungo'),
('Kanam','Kanam'),
('Kankara','Kankara'),
('Kanke','Kanke'),
('Kankia','Kankia'),
('Kano Municipal','Kano Municipal'),
('Karasuwa','Karasuwa'),
('Karaye','Karaye'),
('Karim Lamido','Karim Lamido'),
('Karu','Karu'),
('Katagum','Katagum'),
('Katcha','Katcha'),
('Katsina','Katsina'),
('Katsina-Ala','Katsina-Ala'),
('Kaugama','Kaugama'),
('Kaura','Kaura'),
('Kaura Namoda','Kaura Namoda'),
('Kauru','Kauru'),
('Kazaure','Kazaure'),
('Keana','Keana'),
('Kebbe','Kebbe'),
('Keffi','Keffi'),
('Khana','Khana'),
('Kibiya','Kibiya'),
('Kirfi','Kirfi'),
('Kiri Kasama','Kiri Kasama'),
('Kiru','Kiru'),
('Kiyawa','Kiyawa'),
('Kogi','Kogi'),
('Koko/Besse','Koko/Besse'),
('Kokona','Kokona'),
('Kolokuma/Opokuma','Kolokuma/Opokuma'),
('Konduga','Konduga'),
('Konshisha','Konshisha'),
('Kontagora','Kontagora'),
('Kosofe','Kosofe'),
('Kubau','Kubau'),
('Kudan','Kudan'),
('Kuje','Kuje'),
('Kukawa','Kukawa'),
('Kumbotso','Kumbotso'),
('Kumi','Kumi'),
('Kunchi','Kunchi'),
('Kura','Kura'),
('Kurfi','Kurfi'),
('Kusada','Kusada'),
('Kwali','Kwali'),
('Kwami','Kwami'),
('Kwande','Kwande'),
('Kware','Kware'),
('Kwaya Kusar','Kwaya Kusar'),
('Lafia','Lafia'),
('Lagelu','Lagelu'),
('Lagos Island','Lagos Island'),
('Lagos Mainland','Lagos Mainland'),
('Lamurde','Lamurde'),
('Langtang North','Langtang North'),
('Langtang South','Langtang South'),
('Lapai','Lapai'),
('Lau','Lau'),
('Lavun','Lavun'),
('Lere','Lere'),
('Logo','Logo'),
('Lokoja','Lokoja'),
('Machina','Machina'),
('Madagali','Madagali'),
('Madobi','Madobi'),
('Mafa','Mafa'),
('Magama','Magama'),
('Magumeri','Magumeri'),
('Mai"Adua','Mai"Adua'),
('Maiduguri','Maiduguri'),
('Maigatari','Maigatari'),
('Maiha','Maiha'),
('Maiyama','Maiyama'),
('Makarfi','Makarfi'),
('Makoda','Makoda'),
('Makurdi','Makurdi'),
('Malam Madori','Malam Madori'),
('Malumfashi','Malumfashi'),
('Mangu','Mangu'),
('Mani','Mani'),
('Maradun','Maradun'),
('Mariga','Mariga'),
('Marte','Marte'),
('Maru','Maru'),
('Mashegu','Mashegu'),
('Mashi','Mashi'),
('Matazu','Matazu'),
('Mayo Belwa','Mayo Belwa'),
('Mbaitoli','Mbaitoli'),
('Mbo','Mbo'),
('Michika','Michika'),
('Miga','Miga'),
('Mikang','Mikang'),
('Minjibir','Minjibir'),
('Misau','Misau'),
('Mkpat-Enin','Mkpat-Enin'),
('Moba','Moba'),
('Mobbar','Mobbar'),
('Mokwa','Mokwa'),
('Monguno','Monguno'),
('Mopa Muro','Mopa Muro'),
('Moro','Moro'),
('Moya','Moya'),
('Mubi North','Mubi North'),
('Mubi South','Mubi South'),
('Musawa','Musawa'),
('Mushin','Mushin'),
('Nafada','Nafada'),
('Nangere','Nangere'),
('Nasarawa','Nasarawa'),
('Nasarawa','Nasarawa'),
('Nasarawa Egon','Nasarawa Egon'),
('Ndokwa East','Ndokwa East'),
('Ndokwa West','Ndokwa West'),
('Nembe','Nembe'),
('Ngala','Ngala'),
('Nganzai','Nganzai'),
('Ngaski','Ngaski'),
('Ngor Okpala','Ngor Okpala'),
('Nguru','Nguru'),
('Ningi','Ningi'),
('Njaba','Njaba'),
('Njikoka','Njikoka'),
('Nkanu East','Nkanu East'),
('Nkanu West','Nkanu West'),
('Nkwerre','Nkwerre'),
('Nnewi North','Nnewi North'),
('Nnewi South','Nnewi South'),
('Nsit-Atai','Nsit-Atai'),
('Nsit-Ibom','Nsit-Ibom'),
('Nsit-Ubium','Nsit-Ubium'),
('Nsukka','Nsukka'),
('Numan','Numan'),
('Nwangele','Nwangele'),
('Obafemi Owode','Obafemi Owode'),
('Obanliku','Obanliku'),
('Obi','Obi'),
('Obi','Obi'),
('Obi Ngwa','Obi Ngwa'),
('Obio/Akpor','Obio/Akpor'),
('Obokun','Obokun'),
('Obot Akara','Obot Akara'),
('Obowo','Obowo'),
('Obubra','Obubra'),
('Obudu','Obudu'),
('Odeda','Odeda'),
('Odigbo','Odigbo'),
('Odo Otin','Odo Otin'),
('Odogbolu','Odogbolu'),
('Odukpani','Odukpani'),
('Offa','Offa'),
('Ofu','Ofu'),
('Ogba/Egbema/Ndoni','Ogba/Egbema/Ndoni'),
('Ogbadibo','Ogbadibo'),
('Ogbaru','Ogbaru'),
('Ogbia','Ogbia'),
('Ogbomosho North','Ogbomosho North'),
('Ogbomosho South','Ogbomosho South'),
('Ogo Oluwa','Ogo Oluwa'),
('Ogoja','Ogoja'),
('Ogori/Magongo','Ogori/Magongo'),
('Ogu/Bolo','Ogu/Bolo'),
('Ogun Waterside','Ogun Waterside'),
('Oguta','Oguta'),
('Ohafia','Ohafia'),
('Ohaji/Egbema','Ohaji/Egbema'),
('Ohaozara','Ohaozara'),
('Ohaukwu','Ohaukwu'),
('Ohimini','Ohimini'),
('Oji River','Oji River'),
('Ojo','Ojo'),
('Oju','Oju'),
('Oke Ero','Oke Ero'),
('Okehi','Okehi'),
('Okene','Okene'),
('Okigwe','Okigwe'),
('Okitipupa','Okitipupa'),
('Okobo','Okobo'),
('Okpe','Okpe'),
('Okpokwu','Okpokwu'),
('Okrika','Okrika'),
('Ola Oluwa','Ola Oluwa'),
('Olamaboro','Olamaboro'),
('Olorunda','Olorunda'),
('Olorunsogo','Olorunsogo'),
('Oluyole','Oluyole'),
('Omala','Omala'),
('Omuma','Omuma'),
('Ona Ara','Ona Ara'),
('Ondo East','Ondo East'),
('Ondo West','Ondo West'),
('Onicha','Onicha'),
('Onitsha North','Onitsha North'),
('Onitsha South','Onitsha South'),
('Onna','Onna'),
('Opobo/Nkoro','Opobo/Nkoro'),
('Oredo','Oredo'),
('Orelope','Orelope'),
('Orhionmwon','Orhionmwon'),
('Ori Ire','Ori Ire'),
('Oriade','Oriade'),
('Orlu','Orlu'),
('Orolu','Orolu'),
('Oron','Oron'),
('Orsu','Orsu'),
('Oru East','Oru East'),
('Oru West','Oru West'),
('Oruk Anam','Oruk Anam'),
('Orumba North','Orumba North'),
('Orumba South','Orumba South'),
('Ose','Ose'),
('Oshimili North','Oshimili North'),
('Oshimili South','Oshimili South'),
('Oshodi-Isolo','Oshodi-Isolo'),
('Osisioma','Osisioma'),
('Osogbo','Osogbo'),
('Oturkpo','Oturkpo'),
('Ovia North-East','Ovia North-East'),
('Ovia South-West','Ovia South-West'),
('Owan East','Owan East'),
('Owan West','Owan West'),
('Owerri Municipal','Owerri Municipal'),
('Owerri North','Owerri North'),
('Owerri West','Owerri West'),
('Owo','Owo'),
('Oye','Oye'),
('Oyi','Oyi'),
('Oyigbo','Oyigbo'),
('Oyo East','Oyo East'),
('Oyo West','Oyo West'),
('Oyun','Oyun'),
('Paikoro','Paikoro'),
('Pankshin','Pankshin'),
('Patani','Patani'),
('Pategi','Pategi'),
('Port Harcourt','Port Harcourt'),
('Potiskum','Potiskum'),
('Qua"an Pan','Qua"an Pan'),
('Rabah','Rabah'),
('Rafi','Rafi'),
('Rano','Rano'),
('Remo North','Remo North'),
('Rijau','Rijau'),
('Rimi','Rimi'),
('Rimin Gado','Rimin Gado'),
('Ringim','Ringim'),
('Riyom','Riyom'),
('Rogo','Rogo'),
('Roni','Roni'),
('Sabon Birni','Sabon Birni'),
('Sabon Gari','Sabon Gari'),
('Sabuwa','Sabuwa'),
('Safana','Safana'),
('Sagbama','Sagbama'),
('Sakaba','Sakaba'),
('Saki East','Saki East'),
('Saki West','Saki West'),
('Sandamu','Sandamu'),
('Sanga','Sanga'),
('Sapele','Sapele'),
('Sardauna','Sardauna'),
('Shagamu','Shagamu'),
('Shagari','Shagari'),
('Shanga','Shanga'),
('Shani','Shani'),
('Shanono','Shanono'),
('Shelleng','Shelleng'),
('Shendam','Shendam'),
('Shinkafi','Shinkafi'),
('Shira','Shira'),
('Shiroro','Shiroro'),
('Shomolu','Shomolu'),
('Shongom','Shongom'),
('Silame','Silame'),
('Soba','Soba'),
('Sokoto North','Sokoto North'),
('Sokoto South','Sokoto South'),
('Song','Song'),
('Southern Ijaw','Southern Ijaw'),
('Sule Tankarkar','Sule Tankarkar'),
('Suleja','Suleja'),
('Sumaila','Sumaila'),
('Suru','Suru'),
('Surulere','Surulere'),
('Surulere','Surulere'),
('Tafa','Tafa'),
('Tafawa Balewa','Tafawa Balewa'),
('Tai','Tai'),
('Takai','Takai'),
('Takum','Takum'),
('Talata Mafara','Talata Mafara'),
('Tambuwal','Tambuwal'),
('Tangaza','Tangaza'),
('Tarauni','Tarauni'),
('Tarka','Tarka'),
('Tarmuwa','Tarmuwa'),
('Taura','Taura'),
('Tofa','Tofa'),
('Toro','Toro'),
('Toto','Toto'),
('Toungo','Toungo'),
('Tsanyawa','Tsanyawa'),
('Tudun Wada','Tudun Wada'),
('Tureta','Tureta'),
('Udenu','Udenu'),
('Udi','Udi'),
('Udu','Udu'),
('Udung-Uko','Udung-Uko'),
('Ughelli North','Ughelli North'),
('Ughelli South','Ughelli South'),
('Ugwunagbo','Ugwunagbo'),
('Uhunmwonde','Uhunmwonde'),
('Ukanafun','Ukanafun'),
('Ukum','Ukum'),
('Ukwa East','Ukwa East'),
('Ukwa West','Ukwa West'),
('Ukwuani','Ukwuani'),
('Umu Nneochi','Umu Nneochi'),
('Umuahia North','Umuahia North'),
('Umuahia South','Umuahia South'),
('Ungogo','Ungogo'),
('Unuimo','Unuimo'),
('Uruan','Uruan'),
('Urue-Offong/Oruko','Urue-Offong/Oruko'),
('Ushongo','Ushongo'),
('Ussa','Ussa'),
('Uvwie','Uvwie'),
('Uyo','Uyo'),
('Uzo-Uwani','Uzo-Uwani'),
('Vandeikya','Vandeikya'),
('Wamako','Wamako'),
('Wamba','Wamba'),
('Warawa','Warawa'),
('Warji','Warji'),
('Warri North','Warri North'),
('Warri South','Warri South'),
('Warri South West','Warri South West'),
('Wase','Wase'),
('Wudil','Wudil'),
('Wukari','Wukari'),
('Wurno','Wurno'),
('Wushishi','Wushishi'),
('Yabo','Yabo'),
('Yagba East','Yagba East'),
('Yagba West','Yagba West'),
('Yakuur','Yakuur'),
('Yala','Yala'),
('Yamaltu/Deba','Yamaltu/Deba'),
('Yankwashi','Yankwashi'),
('Yauri','Yauri'),
('Yenagoa','Yenagoa'),
('Yewa North','Yewa North'),
('Yewa South','Yewa South'),
('Yola North','Yola North'),
('Yola South','Yola South'),
('Yorro','Yorro'),
('Yunusari','Yunusari'),
('Yusufari','Yusufari'),
('Zaki','Zaki'),
('Zango','Zango'),
('Zangon Kataf','Zangon Kataf'),
('Zaria','Zaria'),
('Zing','Zing'),
('Zurmi','Zurmi'),
('Zuru','Zuru')
)    





GENDER_CHOICES = (
        ('MALE','Male'),
        ('FEMALE','Female'),
    )
QUALIFICATION_CHOICES = (
        ('SSCE', 'SSCE'),
        ('OND', 'OND'),
        ('NCE', 'NCE'),
        ('HND', 'HND'),
        ('BSC','BSC'),
        ('MASTERS','MASTERS'),
        ('PHD', 'PHD')
    )


class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    middle_name = models.CharField(max_length=20)
    date_of_birth = models.DateField(null=True)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES)
    home_address = models.CharField(max_length=50,blank=False)
    state = models.CharField(max_length=12, choices=STATE_CHOICES)
    lga = models.CharField(max_length=10)
    language_spoken = MultiSelectField(max_length=20, choices=Lang_choice, max_choices=4)
    city = models.CharField(max_length=300, null=True)



    def __str__(self):
        return f'profile for Client {self.username}'



   

class Freelancer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='user')
    middle_name = models.CharField(max_length=20)
    date_of_birth = models.DateField(null=True)
    nin = models.CharField(max_length=11)
    skill = models.CharField(max_length=20, blank=False)
    profile_pic = models.ImageField(upload_to='profiles', blank=True, null=True)
    work_address = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=12, choices=STATE_CHOICES)
    lga = models.CharField(max_length=30, choices=LGA_CHOICES)
    city = models.CharField(max_length=300, null=True)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES)
    Trade_Test_or_License = models.ImageField(upload_to='tradecerts', null=True, blank=True)
    qualification = models.CharField(max_length=1000, choices=QUALIFICATION_CHOICES)
    is_active = models.BooleanField(default=False)
    Referral_Username = models.CharField(max_length=110, null=True, blank=True, default='SkilledCheck')
    Bank_Name = models.CharField(max_length=200, choices=BANK_CHOICES, default="Jaiz")
    Bank_Account_Number = models.CharField(max_length=10, null=False, blank=False, default="0009410323")
    language_spoken = models.CharField(max_length=200)
    check_to_accept_terms_and_condition = models.BooleanField(default=False)
    otp = models.CharField(max_length=100, null=True, blank=True)
    uid = models.UUIDField(default=uuid.uuid4)
    phone_number = models.CharField(max_length=16, validators=[phone_validator], unique=True)
    last_login = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return f'Profile for Freelancer {self.user.username}'



   